#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace findBarcode
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LKSDB")]
	public partial class barkodDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public barkodDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LKSDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public barkodDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public barkodDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public barkodDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public barkodDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PAZ_DEPOBAZLISTOKFIYAT> PAZ_DEPOBAZLISTOKFIYATs
		{
			get
			{
				return this.GetTable<PAZ_DEPOBAZLISTOKFIYAT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAZ_DEPOBAZLISTOKFIYAT")]
	public partial class PAZ_DEPOBAZLISTOKFIYAT
	{
		
		private string _CODE;
		
		private string _NAME;
		
		private string _BIRIM;
		
		private string _BARCODE;
		
		private System.Nullable<double> _ALISFIYATI;
		
		private System.Nullable<double> _SATISFIYATI;
		
		private System.Nullable<double> _GATEMSTOK;
		
		private System.Nullable<double> _KÜSGETSTOK;
		
		private System.Nullable<double> _TOPLAMSTOK;
		
		private System.Nullable<double> _GATEMTUTAR;
		
		private System.Nullable<double> _KÜSGETTUTAR;
		
		private System.Nullable<double> _GENELTUTAR;
		
		public PAZ_DEPOBAZLISTOKFIYAT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(25)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(51)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRIM", DbType="VarChar(11)")]
		public string BIRIM
		{
			get
			{
				return this._BIRIM;
			}
			set
			{
				if ((this._BIRIM != value))
				{
					this._BIRIM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="VarChar(101)")]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this._BARCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALISFIYATI", DbType="Float")]
		public System.Nullable<double> ALISFIYATI
		{
			get
			{
				return this._ALISFIYATI;
			}
			set
			{
				if ((this._ALISFIYATI != value))
				{
					this._ALISFIYATI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SATISFIYATI", DbType="Float")]
		public System.Nullable<double> SATISFIYATI
		{
			get
			{
				return this._SATISFIYATI;
			}
			set
			{
				if ((this._SATISFIYATI != value))
				{
					this._SATISFIYATI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GATEMSTOK", DbType="Float")]
		public System.Nullable<double> GATEMSTOK
		{
			get
			{
				return this._GATEMSTOK;
			}
			set
			{
				if ((this._GATEMSTOK != value))
				{
					this._GATEMSTOK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KÜSGETSTOK", DbType="Float")]
		public System.Nullable<double> KÜSGETSTOK
		{
			get
			{
				return this._KÜSGETSTOK;
			}
			set
			{
				if ((this._KÜSGETSTOK != value))
				{
					this._KÜSGETSTOK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOPLAMSTOK", DbType="Float")]
		public System.Nullable<double> TOPLAMSTOK
		{
			get
			{
				return this._TOPLAMSTOK;
			}
			set
			{
				if ((this._TOPLAMSTOK != value))
				{
					this._TOPLAMSTOK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GATEMTUTAR", DbType="Float")]
		public System.Nullable<double> GATEMTUTAR
		{
			get
			{
				return this._GATEMTUTAR;
			}
			set
			{
				if ((this._GATEMTUTAR != value))
				{
					this._GATEMTUTAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KÜSGETTUTAR", DbType="Float")]
		public System.Nullable<double> KÜSGETTUTAR
		{
			get
			{
				return this._KÜSGETTUTAR;
			}
			set
			{
				if ((this._KÜSGETTUTAR != value))
				{
					this._KÜSGETTUTAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENELTUTAR", DbType="Float")]
		public System.Nullable<double> GENELTUTAR
		{
			get
			{
				return this._GENELTUTAR;
			}
			set
			{
				if ((this._GENELTUTAR != value))
				{
					this._GENELTUTAR = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
